### PR TITLE
turns out we do not use omniauthable; just disable

### PR DESCRIPTION
**Pull request by peetucket**

### CODE REVIEW

**Comment by jcoyne** [comment]
@peetucket can we remove the Gem too?

**Comment by peetucket** [comment]
> @peetucket can we remove the Gem too?

yes, pushed another commit

**Comment by jcoyne** [comment]
What about the `omniauth` gem itself? https://github.com/sul-dlss/revs/blob/a0b19b27198cda9dd5efdf57cabc6018ea702cae/Gemfile#L18

**Comment by peetucket** [comment]
> What about the `omniauth` gem itself?
> 
> https://github.com/sul-dlss/revs/blob/a0b19b27198cda9dd5efdf57cabc6018ea702cae/Gemfile#L18

Oh yes, I think we can.  Pushed another commit.  Works locally, let's see if the tests pass.  I can squash commits too before merge.

**Pull request merged**
