### PR TITLE
add per page option to favorites screen

### LINKED ISSUE #67: Add the ability to select the "per page" shown for favorites on user profile pages

### PR DESCRIPTION
**Pull request by peetucket**
fixes #67

### CODE REVIEW

**Comment by ggeisler** [comment]
@peetucket Can you post a screenshot of the page after the per_page option is added?

**Comment by peetucket** [comment]
Only shown on favorites or galleries page (per user)
Auto-submits when selecting a new value

revs_digital_library__my_gallery_

revs_digital_library__admin1__favorites_and_1____sites_development_revs__bash_

**Comment by ggeisler** [comment]
Thanks. Can you get it so that the per page dropdown is on the same line as the "1 - 3 of 3" text? The current arrangement uses more vertical space while leaving a lot of empty horizontal space, and moves the view option links farther from the result items. Ideally it would be something like this, aligned to the right as the "1 - 3 of 3" currently is:

Per page [25 ^]   Showing 1 - 3 of 3 items

I can do it if you'd rather but I won't be able to get to it until next week.

**Comment by peetucket** [comment]
how about this?

screen shot 2016-09-15 at 12 57 38 pm

**Comment by ggeisler** [comment]
Sure, looks good.

**Pull request merged**
