### PR TITLE
block malicious user registrations

### PR DESCRIPTION
**Pull request by peetucket**
- Provide an option that requires users to answer a registration question in order to complete registration
- Provide an option to require users to have their accounts manually activated by an administrator
- Receive a daily email with new account registrations that are inactive
- Block user registrations with known malicious username patterns (based on regex)

### CODE REVIEW

**Comment by ggeisler** [comment]
Did #89 not work? Not clear on why you are already trying an additional approach.

I really don't think this approach is a good idea, from a UX perspective. While most legitimate users wanting to register will have automotive domain knowledge, it seems unreasonable to require every new user to have the necessary domain knowledge to answer an automotive-related question. What if a cultural studies researcher is told by a colleague that the Revs site has a lot of photos of people socializing in the 1960's. The researcher knows nothing about cars but is legitimately interested in the many crowd photos. Rejecting that researcher for not knowing the answer to an automotive-related question seems very wrong to me. It'll frustrate and make the user feel stupid, which are fundamental things you want to avoid when designing a good user experience.

I've never registered for a website that required me to answer a question that required domain knowledge.

**Comment by peetucket** [comment]
#89 didn't stop them, so it is clearly malicious humans registering about 10-15 accounts per day.  They are confirming their email addresses, so they have active accounts, but based on what they are entering in their bios (spammy links to other websites) and the random nature of their usernames, I'm sure they are not legitimate.

The only other approach I can think of is making accounts inactive by default and then I would approve them manually.  There are only a few legitimate accounts per week (likely to drop even more after the transfer) so the load would not be high, though I would need to build some sort of easy approval process and email notification to do this.

**Comment by ggeisler** [comment]
I see. Well, the manual approval process sounds better to me, but that's easy for me to say since I wouldn't be doing it. So I'll leave it up to you on which approach to go with. If you want me to merge this PR I will. I just wanted to document my UX concern about the approach used in this PR.

**Comment by peetucket** [comment]
agreed it is not ideal.  One approach I've seen in the past to block bots is a simple math question, but that won't work for humans.  let me deploy the branch and see it if actually works before you merge.  Anyway, I can always work on the manual approval approach and make it configurable so we can deploy that when ready.  Also, note that even after mege, we can easily disable the reg questions by setting the questions configured in the application.rb to blank (it is coded to not show or check if there are no questions in the config).

**Comment by peetucket** [comment]
only a couple new registrations yesterday, and it is not clear if they are spammy or not (possible but not following the obvious patterns of every other day this month, so could be legit)

its' quite possible that if we leave the questions in place for a couple weeks, we will chase them away and then we can shut them off again

**Pull request merged**
